cicirello/Chips-n-Salsa

examples/README.md

Revised examples/README to account for Issue #2 .  fixes #2

Simplify entrypoint

---

README.md

- Added README links for accessibility
- Whitespace cleanup

Links for accessibility

---

.github/workflows/api-website.yml
.github/workflows/maven-publish.yml
pom.xml

* Upgrade various GitHub Actions versions used in workflows
* Added nexus-staging-maven-plugin to pom.xml to streamline deployment process

Various workflow and deployment updates

---

CHANGELOG.md
src/org/cicirello/search/problems/scheduling/ShortestProcessingPlusSetupTimePrecompute.java
src/org/cicirello/search/problems/scheduling/ShortestProcessingTime.java
src/org/cicirello/search/problems/scheduling/SmallestSetupPrecompute.java
src/org/cicirello/search/problems/scheduling/WeightedShortestProcessingPlusSetupTimePrecompute.java
src/org/cicirello/search/ss/HybridConstructiveHeuristic.java
tests/org/cicirello/search/concurrent/TimedParallelMultistarterTests.java
tests/org/cicirello/search/problems/scheduling/HeuristicTests.java
tests/org/cicirello/search/ss/HybridConstructiveHeuristicTests.java

* Added HybridConstructiveHeuristic, which provides the ability
to use multiple heuristics with a stochastic sampling search,
where a heuristic is chosen from a set of constructive heuristics
at the start of each iteration of the stochastic sampler and used
for all decisions made during that iteration. The class supports the
following strategies for selecting the next heuristic:
* Heuristic uniformly at random from among the available heuristics.
* Heuristic chosen using a round robin strategy that systematically cycles
over the heuristics.
* Heuristic chosen via a weighted random selection process.

Added support for multiheuristic stochastic sampling search  

---

CHANGELOG.md
src/org/cicirello/search/problems/OneMax.java
src/org/cicirello/search/problems/Trap.java
src/org/cicirello/search/problems/TwoMax.java
src/org/cicirello/search/problems/TwoMaxEqualPeaks.java
tests/org/cicirello/search/problems/TrapTests.java
tests/org/cicirello/search/problems/TwoMaxTests.java

Added TwoMax, TwoMaxEqualPeaks, and Trap.

Added a few optimization problem implementations

---

CHANGELOG.md
src/org/cicirello/search/problems/Trap.java
tests/org/cicirello/search/problems/TrapTests.java

Fixes bug in definition of Trap function. Previous implementation was based on a secondary source, but upon consulting original problem definition of Ackley, an error was detected. This pull request fixes it.
Fixes #235

Patch trap function

---

CHANGELOG.md
src/org/cicirello/search/problems/Plateaus.java
src/org/cicirello/search/representations/BitVector.java
tests/org/cicirello/search/problems/PlateausTests.java
tests/org/cicirello/search/representations/BitVectorTests.java

Implementation of the Plateaus problem.
Closes #232

Implementation of the Plateaus problem

---

CHANGELOG.md
src/org/cicirello/search/problems/Mix.java
src/org/cicirello/search/representations/BitVector.java
tests/org/cicirello/search/problems/MixTests.java
tests/org/cicirello/search/representations/BitVectorTests.java

Implements the Mix search landscape, and also includes enhancements to the BitVector class.
Closes #233

Mix landscape, and BitVector enhancements

---

CHANGELOG.md
src/org/cicirello/search/operators/permutations/ThreeOptMutation.java
tests/org/cicirello/search/operators/permutations/ThreeOptMutationTests.java

Added ThreeOptMutation.
Closes #229

Three opt neighborhood

---

docs/index.html

Minor documentation bug fix.
Closes #273

Minor documentation bug fix.

---

CHANGELOG.md
src/org/cicirello/search/problems/HollandRoyalRoad.java
src/org/cicirello/search/problems/RoyalRoad.java
tests/org/cicirello/search/problems/HollandRoyalRoadTests.java
tests/org/cicirello/search/problems/RoyalRoadTests.java

Implementations of royal road functions (original R1 and R2 functions of Mitchell, Forest, and Holland, as well as Holland's later version).
Closes #234

Royal road functions (original R1 and R2 functions, as well as Holland's)

---

CHANGELOG.md
src/org/cicirello/search/sa/AcceptanceTracker.java

Corrected acceptance rate calculations in AcceptanceTracker class for  cases where some runs terminated early upon finding solution with cost equal to theoretical minimum cost for problem.
Closes #278

Fixed bug in AcceptanceTracker class

---

CHANGELOG.md
src/org/cicirello/search/problems/ForresterEtAl2008.java
src/org/cicirello/search/problems/GramacyLee2012.java
tests/org/cicirello/search/problems/ContinuousTests.java

Added the following:
* Implementation of Forrester et al (2008) continuous function optimization problem.
* Implementation of Gramacy and Lee (2012) continuous function optimization problem.
Closes #285 
Closes #286

Continuous function optimization problems

---

CHANGELOG.md
src/org/cicirello/search/sa/SelfTuningLam.java
tests/org/cicirello/search/sa/SelfTuningLamTests.java

Added implementation of the Self-Tuning Lam annealing schedule (class SelfTuningLam), as described by the paper: Vincent A. Cicirello. 2021. Self-Tuning Lam Annealing: Learning Hyperparameters While Problem Solving. Preprint, under review (September 2021).
Closes #288

Added implementation of the Self-Tuning Lam annealing schedule

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/reals/GaussianMutation.java

Refactored GaussianMutation to improve maintainability by eliminating dependence upon a specific algorithm for generating Gaussian distributed random numbers.
Closes #300

Refactored GaussianMutation to eliminate dependence upon a specific Gaussian algorithm

---

pom.xml
src/test/java/org/cicirello/search/ss/HybridConstructiveHeuristicTests.java

Includes the following:
* Fixed test bug due to random chance. 
* Added transitive dependencies explicitly to pom.xml.

pom.xml change and test case bug fix

---

CHANGELOG.md
src/main/java/org/cicirello/search/ProgressTracker.java
src/main/java/org/cicirello/search/hc/FirstDescentHillClimber.java
src/main/java/org/cicirello/search/hc/SteepestDescentHillClimber.java
src/main/java/org/cicirello/search/sa/SimulatedAnnealing.java
src/main/java/org/cicirello/search/ss/AbstractStochasticSampler.java
src/main/java/org/cicirello/search/ss/HeuristicSolutionGenerator.java
src/test/java/org/cicirello/search/ProgressTrackerTests.java
src/test/java/org/cicirello/search/concurrent/ParallelMultistarterSingleThreadTests.java
src/test/java/org/cicirello/search/concurrent/ParallelMultistarterTwoThreadsTests.java
src/test/java/org/cicirello/search/concurrent/ParallelReoptimizableMultistarterSingleThreadTests.java
src/test/java/org/cicirello/search/concurrent/ParallelReoptimizableMultistarterTwoThreadsTests.java
src/test/java/org/cicirello/search/concurrent/TimedParallelMultistarterTests.java
src/test/java/org/cicirello/search/hc/HillClimberTests.java
src/test/java/org/cicirello/search/restarts/MultistartSearchTests.java
src/test/java/org/cicirello/search/sa/SimulatedAnnealingTests.java
src/test/java/org/cicirello/search/ss/ConstructiveHeuristicTests.java
src/test/java/org/cicirello/search/ss/HybridConstructiveHeuristicTests.java
src/test/java/org/cicirello/search/ss/IterativeSamplingTests.java

Refactored the ProgressTracker class, including:
* Adding new methods to ProgressTracker class:
* `update(int, T, boolean)`
* `update(double, T, boolean)`
* Deprecating the following methods:
* `update(int, T)` in favor of using `update(int, T, boolean)`.
* `update(double, T)` in favor of using `update(double, T, boolean)`.
* `setFoundBest()` in favor of using either `update(int, T, boolean)` 
or `update(double, T, boolean)`.

Refactor class ProgressTracker

---

.github/workflows/build.yml

Updated build.yml workflow to improve the formatting of the PR comments with coverage statistics, by using markdown in the comments.

Update workflow to improve PR coverage comments

---

CHANGELOG.md
src/main/java/org/cicirello/search/problems/tsp/NearestCityHeuristic.java
src/main/java/org/cicirello/search/problems/tsp/NearestCityPairHeuristic.java
src/main/java/org/cicirello/search/problems/tsp/TSP.java
src/test/java/org/cicirello/search/problems/tsp/TSPHeuristicsTests.java
src/test/java/org/cicirello/search/problems/tsp/TSPTests.java

Added constructive heuristics for the TSP for use by stochastic sampling search algorithms.

Constructive heuristics for the TSP for use by stochastic sampling search algorithms

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/GenerationalEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/operators/CrossoverOperator.java
src/main/java/org/cicirello/search/operators/HybridCrossover.java
src/main/java/org/cicirello/search/operators/HybridMutation.java
src/main/java/org/cicirello/search/operators/MutationOperator.java
src/main/java/org/cicirello/search/operators/WeightedHybridCrossover.java
src/main/java/org/cicirello/search/operators/WeightedHybridMutation.java
src/test/java/org/cicirello/search/evo/GenerationalEATests.java
src/test/java/org/cicirello/search/operators/HybridCrossoverTests.java
src/test/java/org/cicirello/search/operators/HybridMutationTests.java

Added a CrossoverOperator interface and integrated it with the GenerationalEvolutionaryAlgorithm class to produce the following EA variations (in addition to the mutation only version preexisting):
* Standard generational model, parents replaced by children, crossover and mutation.
* Generational, parents replaced by children, with mutually exclusive crossover and mutation (i.e., no child is result of both crossover and mutation).
Also includes:
* CrossoverOperator interface for defining custom crossover operators.
* Support for hybrid crossover operators (e.g., picking randomly from set of crossover operators).
Closes #331

Added CrossoverOperator interface and integrated with GenerationalEvolutionaryAlgorithm

---

CHANGELOG.md
pom.xml
src/main/java/org/cicirello/search/ProgressTracker.java
src/main/java/org/cicirello/search/evo/GenerationalMutationOnlyEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/GenerationalNANDOperatorsEvolutionaryAlgorithm.java
src/test/java/org/cicirello/search/evo/GenerationalEANoPTTests.java
src/test/java/org/cicirello/search/evo/GenerationalEATests.java

Refactored evolutionary algorithm classes to improve maintainability, and ease integration of planned future functionality. This PR includes the following:
* Added GenerationalNANDOperatorsEvolutionaryAlgorithm, moving the EA
functionality related to mutually-exclusive genetic operators (i.e., generation variation where
each child is result of either mutation, or crossover, or identical copy of a parent, but never
result of both mutation and crossover) into this new class from the existing 
GenerationalEvolutionaryAlgorithm class.
* Refactored ProgressTracker.update(SolutionCostPair) to simplify logic and increase test coverage.
* Removed all mutually-exclusive genetic operator functionality from the GenerationalEvolutionaryAlgorithm,
moving that functionality into the new …

Refactor EA classes to improve maintainability

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/integers/IntegerValueInitializer.java
src/main/java/org/cicirello/search/operators/integers/IntegerVectorInitializer.java
src/main/java/org/cicirello/search/operators/integers/KPointCrossover.java
src/main/java/org/cicirello/search/operators/integers/RandomValueChangeMutation.java
src/main/java/org/cicirello/search/operators/integers/SinglePointCrossover.java
src/main/java/org/cicirello/search/operators/integers/TwoPointCrossover.java
src/main/java/org/cicirello/search/operators/integers/UndoableRandomValueChangeMutation.java
src/main/java/org/cicirello/search/operators/integers/UndoableUniformMutation.java
src/main/java/org/cicirello/search/operators/integers/UniformCrossover.java
src/main/java/org/cicirello/search/operators/integers/UniformMutation.java
src/main/java/org/cicirello/search/operators/reals/CauchyMutation.java
src/main/java/org/cicirello/search/operators/reals/GaussianMutation.java
src/main/java/org/cicirello/search/operators/reals/RealValueInitializer.java
src/main/java/org/cicirello/search/operators/reals/RealVectorInitializer.java
src/main/java/org/cicirello/search/operators/reals/UndoableCauchyMutation.java
src/main/java/org/cicirello/search/operators/reals/UndoableGaussianMutation.java
src/main/java/org/cicirello/search/operators/reals/UndoableUniformMutation.java
src/main/java/org/cicirello/search/operators/reals/UniformMutation.java
src/main/java/org/cicirello/search/representations/BitVector.java
src/main/java/org/cicirello/search/representations/BoundedIntegerVector.java
src/main/java/org/cicirello/search/representations/BoundedRealVector.java
src/main/java/org/cicirello/search/representations/IntegerVector.java
src/main/java/org/cicirello/search/representations/RealVector.java
src/main/java/org/cicirello/search/representations/SingleInteger.java
src/main/java/org/cicirello/search/representations/SingleReal.java
src/test/java/org/cicirello/search/operators/integers/CrossoverTests.java
src/test/java/org/cicirello/search/representations/NumericRepresentationsTests.java

Crossover operators for integer vectors, including:
* Single-point crossover
* Two-point crossover
* K-point crossover
* Uniform crossover
Enhancements to integer vector classes, including:
* IntegerVector.exchange method which exchanges a subsequence between two IntegerVectors.
* BoundedIntegerVector.sameBounds method which checks if two bounded integer vector are
subject to the same min and max values.
PR also include misc. documentation edits.
Closes #341

Crossover operators for integer vectors

---

.lift.toml

**Summary**
Updates to Lift configuration

Update Lift configuration

---

CHANGELOG.md
pom.xml
src/main/java/org/cicirello/search/operators/reals/KPointCrossover.java
src/main/java/org/cicirello/search/operators/reals/SinglePointCrossover.java
src/main/java/org/cicirello/search/operators/reals/TwoPointCrossover.java
src/main/java/org/cicirello/search/operators/reals/UniformCrossover.java
src/main/java/org/cicirello/search/representations/BoundedRealVector.java
src/main/java/org/cicirello/search/representations/RealVector.java
src/test/java/org/cicirello/search/operators/reals/CrossoverTests.java
src/test/java/org/cicirello/search/representations/NumericRepresentationsTests.java

* Crossover operators for RealVector and BoundedRealVector classes, including:
* Single-point crossover
* Two-point crossover
* K-point crossover
* Uniform crossover
* Enhancements to RealVector and BoundedRealVector, including:
* RealVector.exchange method which exchanges a subsequence between two RealVectors.
* BoundedRealVector.sameBounds method which checks if two bounded real vectors are
subject to the same min and max values.
Closes #342

Crossover operators for RealVector and BoundedRealVector classes

---

README.md
docs/index.html

Minor edits to documentation site and readme

Minor edits to documentation site and readme

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/BasePopulation.java
src/main/java/org/cicirello/search/evo/EliteSet.java
src/main/java/org/cicirello/search/evo/GenerationalEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/GenerationalMutationOnlyEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/GenerationalNANDOperatorsEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/GeneticAlgorithm.java
src/main/java/org/cicirello/search/evo/MutationOnlyGeneticAlgorithm.java
src/main/java/org/cicirello/search/evo/PopulationMember.java
src/test/java/org/cicirello/search/evo/BasePopulationTests.java
src/test/java/org/cicirello/search/evo/EliteSetTests.java
src/test/java/org/cicirello/search/evo/GenerationalEANoPTTests.java
src/test/java/org/cicirello/search/evo/GenerationalEATests.java
src/test/java/org/cicirello/search/evo/GenerationalEAWithElitismTests.java

Enhanced all of the following Evolutionary Algorithm and Genetic Algorithm classes with the option to use elitism:
* GenerationalEvolutionaryAlgorithm
* GenerationalMutationOnlyEvolutionaryAlgorithm
* GenerationalNANDOperatorsEvolutionaryAlgorithm
* GeneticAlgorithm
* MutationOnlyGeneticAlgorithm
Closes #337

Added option to use elitism with Evolutionary Algorithm and Genetic Algorithm classes

---

CHANGELOG.md
docs/index.html
src/main/java/org/cicirello/search/problems/tsp/TSP.java
src/test/java/org/cicirello/search/problems/tsp/TSPTests.java

Added constructors to TSP (traveling salesperson problem) classes to enable specifying problem instance from arrays of x and y coordinates.

Enhancements to TSP classes

---

.github/workflows/docs.yml
README.md

Revised doc workflow to deploy api website to gh-pages branch on release and workflow_dispatch.
Closes #347

Deploy api website to gh-pages branch on release and workflow_dispatch

---

src/test/java/org/cicirello/search/concurrent/TimedParallelMultistarterTests.java
src/test/java/org/cicirello/search/problems/scheduling/HeuristicTests.java
src/test/java/org/cicirello/search/ss/HybridConstructiveHeuristicTests.java

Removed non-printable characters due to copying method signatures from API docs. Theses were identified by Snyk, and all occurrences are in test case code, so no affect on actual library.

Removed hidden chars due to copying method signatures from API docs

---

CHANGELOG.md
pom.xml

Bump org.cicirello.core to 1.1.0

Bump org.cicirello.core to 1.1.0

---

CHANGELOG.md
src/main/java/module-info.java
src/main/java/org/cicirello/search/problems/binpack/Bin.java
src/main/java/org/cicirello/search/problems/binpack/BinPacking.java
src/main/java/org/cicirello/search/problems/binpack/BinPackingSolution.java
src/main/java/org/cicirello/search/problems/binpack/package-info.java
src/test/java/org/cicirello/search/problems/binpack/BinPackingTests.java

Added implementation of the Bin Packing problem, including problem generators.

Added implementation of the bin packing problem

---

CHANGELOG.md
src/main/java/org/cicirello/search/problems/QuadraticAssignmentProblem.java
src/test/java/org/cicirello/search/problems/PermutationInAHaystackTests.java
src/test/java/org/cicirello/search/problems/QAPTests.java

Added implementation of quadratic assignment problem.

Added implementation of quadratic assignment problem

---

CHANGELOG.md
src/main/java/org/cicirello/search/problems/LargestCommonSubgraph.java
src/test/java/org/cicirello/search/concurrent/TimedParallelMultistarterTests.java
src/test/java/org/cicirello/search/problems/LCSTests.java

Added an implementation of the largest common subgraph problem.

Largest Common Subgraph problem implementation

---

CHANGELOG.md
src/main/java/org/cicirello/search/problems/LargestCommonSubgraph.java
src/test/java/org/cicirello/search/problems/LCSTests.java

Added factory method to LargestCommonSubgraph for creation of instances of the problem with strongly regular graphs, specifically such that the instance created consists of a pair of isomorphic Generalized Petersen Graphs.

Factory method to create LCS instance with strongly regular graphs

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/ScrambleMutation.java
src/main/java/org/cicirello/search/operators/permutations/UndoableScrambleMutation.java
src/main/java/org/cicirello/search/operators/permutations/UndoableUniformScrambleMutation.java
src/main/java/org/cicirello/search/operators/permutations/UniformScrambleMutation.java

Eliminated calls to methods deprecated in jpt-3.2.0.
Closes #393

Eliminated calls to methods deprecated in jpt-3.2.0

---

CHANGELOG.md
src/main/java/org/cicirello/search/representations/BitVector.java

Refactored BitVector.exchangeBits and its helper methods.
Closes #401

Improvements to BitVector.exchangeBits and related methods

---

.gitignore
CHANGELOG.md
src/main/java/org/cicirello/search/ss/AbstractStochasticSampler.java
src/main/java/org/cicirello/search/ss/AcceptanceBandSampling.java
src/main/java/org/cicirello/search/ss/ConstructiveHeuristic.java
src/main/java/org/cicirello/search/ss/HeuristicBiasedStochasticSampling.java
src/main/java/org/cicirello/search/ss/HeuristicPermutationGenerator.java
src/main/java/org/cicirello/search/ss/HeuristicSolutionGenerator.java
src/main/java/org/cicirello/search/ss/HybridConstructiveHeuristic.java
src/main/java/org/cicirello/search/ss/IncrementalEvaluation.java
src/main/java/org/cicirello/search/ss/IterativeSampling.java
src/main/java/org/cicirello/search/ss/Partial.java
src/main/java/org/cicirello/search/ss/PartialIntegerVector.java
src/main/java/org/cicirello/search/ss/PartialPermutation.java
src/main/java/org/cicirello/search/ss/ValueBiasedStochasticSampling.java
src/main/java/org/cicirello/search/ss/package-info.java

This PR includes the following:
* Refactored hierarchy and methods of stochastic sampling classes.
* Added missing FunctionalInterface annotation on HeuristicBiasedStochasticSampling.BiasFunction.
* Added missing FunctionalInterface annotation on ValueBiasedStochasticSampling.BiasFunction.
Closes #403

Refactor and other improvements to stochastic samplers

---

src/main/java/module-info.java

Dependency on org.cicirello.core now transitive

Dependency on org.cicirello.core now transitive

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/CycleAlphaMutation.java
src/main/java/org/cicirello/search/operators/permutations/CycleMutation.java
src/test/java/org/cicirello/search/operators/permutations/PermutationMutationTests.java

This PR includes the following:
* Added CycleAlphaMutation: an implementation of the Cycle(alpha) form of cycle mutation.
* Updated documentation of CycleMutation related to recently published paper on cycle mutation.
Closes #413 
Closes #414

Cycle mutation

---

CHANGELOG.md
src/main/java/org/cicirello/search/problems/LargestCommonSubgraph.java
src/main/java/org/cicirello/search/problems/QuadraticAssignmentProblem.java
src/main/java/org/cicirello/search/problems/binpack/BinPacking.java
src/main/java/org/cicirello/search/problems/scheduling/CommonDuedateScheduling.java
src/main/java/org/cicirello/search/problems/scheduling/WeightedStaticScheduling.java
src/main/java/org/cicirello/search/problems/scheduling/WeightedStaticSchedulingWithSetups.java
src/main/java/org/cicirello/search/problems/tsp/RandomTSPMatrix.java
src/main/java/org/cicirello/search/problems/tsp/TSP.java

Utilize Java 17's new RandomGenerator interface where relevant
Closes #419

Utilize Java 17's new RandomGenerator interface where relevant

---

.github/workflows/docs.yml

Fix referrer policy in docs workflow

Fix referrer policy in docs workflow

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/PopulationFitnessVector.java
src/main/java/org/cicirello/search/evo/SigmaScaling.java
src/test/java/org/cicirello/search/evo/PopulationFitnessVectorTests.java
src/test/java/org/cicirello/search/evo/SigmaScalingTests.java
src/test/java/org/cicirello/search/operators/permutations/PermutationMutationTests.java

Added an implementation of sigma scaling for use with the various fitness proportionate selection operators.
Closes #373

Added sigma scaling

---

.github/workflows/jitpack-build.yml

Update url for ahead of time jitpack build

Update url for ahead of time jitpack build

---

.github/workflows/jitpack-build.yml

Revert to prior URL for ahead of time JitPack build

Revert to prior URL for ahead of time JitPack build

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/OnePlusOneEvolutionaryAlgorithm.java
src/test/java/org/cicirello/search/evo/OnePlusOneEATests.java

Added implementation of a (1+1)-EA.
Closes #447

Added implementation of a (1+1)-EA.

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/OnePlusOneEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/OnePlusOneGeneticAlgorithm.java
src/test/java/org/cicirello/search/evo/OnePlusOneGATests.java

Added OnePlusOneGeneticAlgorithm, an implementation of a (1+1)-GA, a subclass of OnePlusOneEvolutionaryAlgorithm for the special case of optimizing a BitVector representation.
Closes #448

Added (1+1)-GA

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/CycleCrossover.java
src/test/java/org/cicirello/search/operators/permutations/CycleCrossoverTests.java

Added implementation of cycle crossover (CX).
Closes #453

Added implementation of cycle crossover

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/CycleCrossover.java
src/main/java/org/cicirello/search/operators/permutations/OrderCrossover.java
src/test/java/org/cicirello/search/operators/permutations/OrderingRelatedCrossoverTests.java

Added Order Crossover (OX), a crossover operator for permutations.
Closes #454

Added Order Crossover (OX), a crossover operator for permutations

---

src/main/java/org/cicirello/search/operators/permutations/UniformOrderBasedCrossover.java
src/test/java/org/cicirello/search/operators/permutations/OrderingRelatedCrossoverTests.java

Optimized implementation of UOBX.

Optimized UOBX

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/CycleCrossover.java
src/main/java/org/cicirello/search/operators/permutations/NonWrappingOrderCrossover.java
src/main/java/org/cicirello/search/operators/permutations/OrderCrossover.java
src/main/java/org/cicirello/search/operators/permutations/PartiallyMatchedCrossover.java
src/main/java/org/cicirello/search/operators/permutations/UniformOrderBasedCrossover.java
src/test/java/org/cicirello/search/operators/permutations/PMXAndRelatedTests.java

Added Partially Matched Crossover (PMX), a crossover operator for permutations.
Closes #457

Added Partially Matched Crossover (PMX)

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/UniformPartiallyMatchedCrossover.java
src/test/java/org/cicirello/search/operators/permutations/PMXAndRelatedTests.java

Added Uniform Partially Matched Crossover (UPMX), a crossover operator for permutations.
Closes #458

Added Uniform Partially Matched Crossover (UPMX)

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/OrderCrossoverTwo.java
src/test/java/org/cicirello/search/operators/permutations/OrderingRelatedCrossoverTests.java

Added Order Crossover 2 (OX2), a crossover operator for permutations.
Closes #475

Added Order Crossover 2 (OX2)

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/EdgeRecombination.java
src/test/java/org/cicirello/search/operators/permutations/EdgeRecombinationTests.java

Added Edge Recombination, a crossover operator for permutations.
Closes #477

Added Edge Recombination

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/EnhancedEdgeRecombination.java
src/test/java/org/cicirello/search/operators/permutations/EdgeRecombinationTests.java

Added Enhanced Edge Recombination, a crossover operator for permutations.
Closes #479

Added Enhanced Edge Recombination

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/BiasedFitnessProportionalSelection.java
src/main/java/org/cicirello/search/evo/BoltzmannBiasFunction.java
src/main/java/org/cicirello/search/evo/BoltzmannSelection.java
src/main/java/org/cicirello/search/evo/ConstantBoltzmannBiasFunction.java
src/main/java/org/cicirello/search/evo/ExponentialCoolingBiasFunction.java
src/main/java/org/cicirello/search/evo/LinearCoolingBiasFunction.java
src/test/java/org/cicirello/search/evo/BoltzmannSelectionTests.java

Added Boltzmann selection with 3 temperature schedules: constant, linear cooling, exponential cooling.
Closes #338

Added Boltzmann selection

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/BiasedStochasticUniversalSampling.java
src/main/java/org/cicirello/search/evo/BoltzmannStochasticUniversalSampling.java
src/test/java/org/cicirello/search/evo/BoltzmannSelectionTests.java
src/test/java/org/cicirello/search/operators/permutations/EdgeRecombinationTests.java

Added Boltzmann selection with stochastic universal sampling, including 3 temperature schedules: constant, linear cooling, exponential cooling.
Closes #484

Added Boltzmann selection with stochastic universal sampling

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/GenerationalEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/GenerationalEvolutionaryAlgorithmMutuallyExclusiveOperators.java
src/main/java/org/cicirello/search/evo/GenerationalMutationOnlyEvolutionaryAlgorithm.java
src/test/java/org/cicirello/search/evo/GenerationalEANoPTTests.java
src/test/java/org/cicirello/search/evo/GenerationalEATests.java
src/test/java/org/cicirello/search/evo/GenerationalEAWithElitismTests.java

For clarity, renamed GenerationalNANDOperatorsEvolutionaryAlgorithm to GenerationalEvolutionaryAlgorithmMutuallyExclusiveOperators (BREAKING CHANGE).
This is a breaking change, though probably a mild one. This class isn't currently used by any known dependents. Additionally, the next release is already planned as a major release that will include additional breaking changes.

Rename class to GenerationalEvolutionaryAlgorithmMutuallyExclusiveOperators 

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/AbstractEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/AbstractPopulation.java
src/main/java/org/cicirello/search/evo/AdaptiveEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/AdaptiveGeneration.java
src/main/java/org/cicirello/search/evo/AlwaysMutateGeneration.java
src/main/java/org/cicirello/search/evo/BasePopulation.java
src/main/java/org/cicirello/search/evo/EncodingWithParameters.java
src/main/java/org/cicirello/search/evo/EvolvableParametersPopulation.java
src/main/java/org/cicirello/search/evo/Generation.java
src/main/java/org/cicirello/search/evo/GenerationalEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/GenerationalEvolutionaryAlgorithmMutuallyExclusiveOperators.java
src/main/java/org/cicirello/search/evo/GenerationalMutationOnlyEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/MutuallyExclusiveGeneration.java
src/main/java/org/cicirello/search/evo/OnlyAlwaysMutateGeneration.java
src/main/java/org/cicirello/search/evo/OnlyMutateGeneration.java
src/main/java/org/cicirello/search/evo/Population.java
src/main/java/org/cicirello/search/evo/SimpleGeneration.java
src/main/java/org/cicirello/search/operators/reals/GaussianMutation.java
src/test/java/org/cicirello/search/evo/AdaptiveEvolutionaryAlgorithmTests.java
src/test/java/org/cicirello/search/evo/AdaptiveGenerationTests.java
src/test/java/org/cicirello/search/evo/BasePopulationTests.java
src/test/java/org/cicirello/search/evo/EncodingWithParametersTests.java
src/test/java/org/cicirello/search/evo/EvolvableParametersPopulationTests.java
src/test/java/org/cicirello/search/evo/GenerationalEATests.java
src/test/java/org/cicirello/search/operators/reals/GaussianMutationTests.java

Added an implementation of an generational evolutionary algorithm with control parameters (crossover and mutation rates) that evolve during the search. The approach is based on what was used in the following two papers:
> Vincent A. Cicirello. "[Genetic Algorithm Parameter Control: Application to Scheduling with Sequence-Dependent Setups](https://www.cicirello.org/publications/cicirello-bict-2015.pdf)". In *Proceedings of the 9th International Conference on Bio-inspired Information and Communications Technologies*, pages 136-143. December 2015.
> Vincent A. Cicirello. "[Impact of Random Number Generation on Parallel Genetic Algorithms](https://www.cicirello.org/publications/cicirello-flairs2018.pdf)". In *Proceedings of the Thirty-First International Florida Artificial Intelligence …

Added an adaptive generational evolutionary algorithm

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/reals/GaussianMutation.java
src/main/java/org/cicirello/search/operators/reals/UndoableGaussianMutation.java
src/test/java/org/cicirello/search/operators/reals/GaussianMutationTests.java

Refactored Gaussian mutation

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/reals/CauchyMutation.java
src/main/java/org/cicirello/search/operators/reals/GaussianMutation.java
src/main/java/org/cicirello/search/operators/reals/UniformMutation.java
src/main/java/org/cicirello/search/representations/BoundedIntegerVector.java
src/main/java/org/cicirello/search/representations/BoundedRealVector.java
src/main/java/org/cicirello/search/representations/IntegerValued.java
src/main/java/org/cicirello/search/representations/IntegerVector.java
src/main/java/org/cicirello/search/representations/RealValued.java
src/main/java/org/cicirello/search/representations/RealVector.java
src/main/java/org/cicirello/search/representations/SingleInteger.java
src/main/java/org/cicirello/search/representations/SingleReal.java
src/test/java/org/cicirello/search/operators/reals/CauchyMutationTests.java
src/test/java/org/cicirello/search/operators/reals/GaussianMutationTests.java
src/test/java/org/cicirello/search/operators/reals/UniformMutationTests.java
src/test/java/org/cicirello/search/representations/NumericRepresentationsTests.java

Added:
* A set(int[]) method to the IntegerValued interface along with implementations in corresponding classes.
* A set(double[]) method to the RealValued interface along with implementations in corresponding classes.
Closes #502

Set vector representations from arrays

---

src/main/java/org/cicirello/search/operators/reals/UndoableCauchyMutation.java
src/main/java/org/cicirello/search/operators/reals/UndoableGaussianMutation.java
src/main/java/org/cicirello/search/operators/reals/UndoableUniformMutation.java

Minor optimization to undo method of the mutation ops for real-valued representations

Minor optimization to undo method of the mutation ops for real-valued representations

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/reals/AbstractRealMutation.java
src/main/java/org/cicirello/search/operators/reals/AbstractUndoableRealMutation.java
src/main/java/org/cicirello/search/operators/reals/GaussianMutation.java
src/main/java/org/cicirello/search/operators/reals/UndoableGaussianMutation.java
src/test/java/org/cicirello/search/operators/reals/GaussianMutationTests.java

Extracted an internal abstract base class for common functionality of the real-valued mutation operators (this is part of #505 and #506). Refactored Gaussian mutation classes to use new abstract base class.

Extracted an abstract base class for common functionality of mutation for real-valued representations

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/reals/CauchyMutation.java
src/main/java/org/cicirello/search/operators/reals/UndoableCauchyMutation.java
src/test/java/org/cicirello/search/operators/reals/CauchyMutationTests.java

Added a factory method in Cauchy mutation operator classes that constrains result to an interval.
Closes #512

Added a factory method in Cauchy mutation classes constraining result to an interval

---

src/test/java/org/cicirello/search/evo/TruncationSelectionInternalMethodTests.java

Refactored truncation selection test cases (suggested by Sonatype Lift Technical Debt Scan)
Closes #522

Refactored truncation selection test cases (suggested by Sonatype Lift Technical Debt Scan)

---

CHANGELOG.md
src/test/java/org/cicirello/search/operators/reals/SharedTestRealMutationOps.java

Refactored test cases for real-valued mutation operators (suggested by Sonatype Lift's Technical Debt scan)
Closes #524

Refactored test cases for real-valued mutation operators (suggested by Sonatype Lift's Technical Debt scan)

---

src/test/java/org/cicirello/search/problems/tsp/RandomTSPDoubleMatrixTests.java
src/test/java/org/cicirello/search/problems/tsp/RandomTSPIntegerMatrixTests.java

Refactored test class RandomTSPMatrixTests (suggested by Sonatype Lift's Technical Debt scan)
Closes #515

Refactored test class RandomTSPMatrixTests (suggested by Sonatype Lift's Technical Debt scan)

---

src/test/java/org/cicirello/search/evo/BasePopulationTests.java
src/test/java/org/cicirello/search/evo/EvolvableParametersPopulationTests.java
src/test/java/org/cicirello/search/evo/SharedTestPopulations.java

Refactored test cases for the population classes into a hierarchy, extracting a common base class, to reduce redundancy. Based on suggestion by Sonatype Lift's new technical debt scan.
Closes #516 
Closes #527

Refactored test cases for population classes (suggested by Sonatype Lift Technical Debt scan)

---

CHANGELOG.md
pom.xml
src/main/java/org/cicirello/search/evo/FitnessShifter.java
src/test/java/org/cicirello/search/evo/OnePlusOneEATests.java

Bump jpt from 4.3.0 to 4.3.1

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/CycleCrossover.java
src/main/java/org/cicirello/search/operators/permutations/EdgeRecombination.java
src/main/java/org/cicirello/search/operators/permutations/EnhancedEdgeRecombination.java
src/main/java/org/cicirello/search/operators/permutations/NonWrappingOrderCrossover.java
src/main/java/org/cicirello/search/operators/permutations/OrderCrossover.java
src/main/java/org/cicirello/search/operators/permutations/OrderCrossoverTwo.java
src/main/java/org/cicirello/search/operators/permutations/PrecedencePreservativeCrossover.java
src/main/java/org/cicirello/search/operators/permutations/UndoableScrambleMutation.java
src/main/java/org/cicirello/search/operators/permutations/UndoableUniformScrambleMutation.java
src/main/java/org/cicirello/search/operators/permutations/UniformOrderBasedCrossover.java
src/main/java/org/cicirello/search/operators/permutations/UniformPrecedencePreservativeCrossover.java
src/main/java/org/cicirello/search/operators/reals/AbstractRealMutation.java
src/main/java/org/cicirello/search/operators/reals/AbstractUndoableRealMutation.java
src/main/java/org/cicirello/search/operators/reals/CauchyMutation.java
src/main/java/org/cicirello/search/operators/reals/GaussianMutation.java
src/main/java/org/cicirello/search/operators/reals/UndoableCauchyMutation.java
src/main/java/org/cicirello/search/operators/reals/UndoableGaussianMutation.java
src/main/java/org/cicirello/search/operators/reals/UndoableUniformMutation.java
src/main/java/org/cicirello/search/operators/reals/UniformMutation.java

* Refactored several permutation crossover and mutation operators for improved performance.
* Refactored all real-valued mutation operators.

Refactored operators for permutations and real-valued reps

---

CHANGELOG.md
src/main/java/org/cicirello/search/problems/tsp/EuclideanDistance.java
src/main/java/org/cicirello/search/problems/tsp/TSP.java
src/test/java/org/cicirello/search/problems/tsp/EuclideanDistanceTests.java

Extracted a EuclideanDistance class from the TSP where previously default and only edge distance to enable easily introducing additional TSP edge distance functions.

Extracted EuclideanDistance class from TSP class

---

CHANGELOG.md
src/main/java/org/cicirello/search/sa/SimulatedAnnealing.java
src/test/java/org/cicirello/search/sa/SimulatedAnnealingHCTests.java

Misc improvements to the SimulatedAnnealing class. No functional changes.

Refactored SimulatedAnnealing

---

CHANGELOG.md
src/main/java/org/cicirello/search/hc/AbstractHillClimber.java
src/main/java/org/cicirello/search/hc/FirstDescentHillClimber.java
src/main/java/org/cicirello/search/hc/SteepestDescentHillClimber.java
src/main/java/org/cicirello/search/restarts/Multistarter.java
src/main/java/org/cicirello/search/restarts/ReoptimizableMultistarter.java
src/main/java/org/cicirello/search/ss/AbstractStochasticSampler.java
src/main/java/org/cicirello/search/ss/IterativeSampling.java
src/test/java/org/cicirello/search/hc/FirstDescentHillClimberTests.java
src/test/java/org/cicirello/search/hc/HillClimberTests.java
src/test/java/org/cicirello/search/hc/SharedTestHillClimberHelpers.java
src/test/java/org/cicirello/search/hc/SteepestDescentHillClimberTests.java

* Refactored hill climber classes and stochastic sampling classes to improve performance and/or maintainability.
* Refactored test cases for the hill climber classes (based on RefactorFirst scan).

Refactored hill climbers and their test cases and stochastic samplers

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/AbstractWeightedSelection.java
src/main/java/org/cicirello/search/evo/AdaptiveEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/BaseElitistPopulation.java
src/main/java/org/cicirello/search/evo/BasePopulation.java
src/main/java/org/cicirello/search/evo/EncodingWithParameters.java
src/main/java/org/cicirello/search/evo/EvolvableParametersElitistPopulation.java
src/main/java/org/cicirello/search/evo/EvolvableParametersPopulation.java
src/main/java/org/cicirello/search/evo/GenerationalEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/GenerationalEvolutionaryAlgorithmMutuallyExclusiveOperators.java
src/main/java/org/cicirello/search/evo/GenerationalMutationOnlyEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/OnePlusOneEvolutionaryAlgorithm.java
src/test/java/org/cicirello/search/evo/AdaptiveGenerationTests.java
src/test/java/org/cicirello/search/evo/BaseElitistPopulationTests.java
src/test/java/org/cicirello/search/evo/BasePopulationTests.java
src/test/java/org/cicirello/search/evo/EvolvableParametersElitistPopulationTests.java
src/test/java/org/cicirello/search/evo/EvolvableParametersPopulationTests.java

Refactored evolutionary algorithms to make various improvements related to performance and/or maintainability.

Refactored evolutionary algorithms

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/AdaptiveMutationOnlyEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/AdaptiveMutationOnlyGeneration.java
src/test/java/org/cicirello/search/evo/AdaptiveMutationOnlyEvolutionaryAlgorithmTests.java
src/test/java/org/cicirello/search/evo/AdaptiveMutationOnlyGenerationTests.java
src/test/java/org/cicirello/search/evo/OnePlusOneEATests.java

AdaptiveMutationOnlyEvolutionaryAlgorithm: An implementation of a mutation-only evolutionary algorithm with mutation rates that evolve during the search.
Closes #500

Added adaptive mutation-only evolutionary algorithms

---

CHANGELOG.md
README.md
pom.xml
src/main/java/module-info.java
src/main/java/org/cicirello/search/concurrent/CallableOptimizerFactory.java
src/main/java/org/cicirello/search/concurrent/CallableReoptimizerFactory.java
src/main/java/org/cicirello/search/concurrent/ParallelMetaheuristic.java
src/main/java/org/cicirello/search/concurrent/ParallelMultistarter.java
src/main/java/org/cicirello/search/concurrent/ParallelMultistarterUtil.java
src/main/java/org/cicirello/search/concurrent/ParallelReoptimizableMetaheuristic.java
src/main/java/org/cicirello/search/concurrent/ParallelReoptimizableMultistarter.java
src/main/java/org/cicirello/search/concurrent/Splittable.java
src/main/java/org/cicirello/search/concurrent/TimedParallelMultistarter.java
src/main/java/org/cicirello/search/concurrent/TimedParallelReoptimizableMultistarter.java

Refactored parallel metaheuristic and parallel multistarter classes.

Refactor parallel metaheuristic and parallel multistarter classes

---

CHANGELOG.md

Prepare release 6.2.0

---

CHANGELOG.md
src/test/java/org/cicirello/search/operators/permutations/IterableMutationTests.java

Refactored test cases for all of the iterable mutation operators based on RefactorFirst scan.
Closes #575

Refactored test cases for all of the iterable mutation operators

---

CHANGELOG.md
src/test/java/org/cicirello/search/operators/integers/UniformMutationTests.java

Refactored test cases for UniformMutation for integer representations
Closes #587

Refactored test cases for UniformMutation for integer representations

---

CHANGELOG.md
src/main/java/org/cicirello/search/problems/scheduling/CommonDuedateInstanceReader.java
src/main/java/org/cicirello/search/problems/scheduling/CommonDuedateInstanceWriter.java
src/main/java/org/cicirello/search/problems/scheduling/CommonDuedateScheduling.java
src/test/java/org/cicirello/search/problems/scheduling/CDDTests.java
src/test/java/org/cicirello/search/problems/scheduling/CommoDuedateSchedulingTests.java
src/test/java/org/cicirello/search/problems/scheduling/CommonDuedateInstanceIOTests.java

This PR includes the following:
* Refactored CommonDuedateScheduling (based on RefactorFirst scan) to extract internal package-access classes for reading and writing instances to and from OR-library formatted files.
* Refactored test cases for CommonDuedateScheduling (also based on RefactorFirst scan)
Closes #576 
Closes #589

Refactored CommonDuedateScheduling

---

CHANGELOG.md
src/main/java/org/cicirello/search/problems/scheduling/CommonDuedateInstanceWriter.java
src/main/java/org/cicirello/search/problems/scheduling/WeightedStaticScheduling.java
src/main/java/org/cicirello/search/problems/scheduling/WeightedStaticSchedulingReader.java
src/main/java/org/cicirello/search/problems/scheduling/WeightedStaticSchedulingWithSetups.java
src/main/java/org/cicirello/search/problems/scheduling/WeightedStaticSchedulingWithSetupsReader.java
src/main/java/org/cicirello/search/problems/scheduling/WeightedStaticSchedulingWithSetupsWriter.java
src/main/java/org/cicirello/search/problems/scheduling/WeightedStaticSchedulingWriter.java
src/test/java/org/cicirello/search/problems/scheduling/WeightedStaticIOTests.java
src/test/java/org/cicirello/search/problems/scheduling/WeightedStaticSetupsIOTests.java
src/test/java/org/cicirello/search/problems/scheduling/WeightedStaticSetupsTests.java
src/test/java/org/cicirello/search/problems/scheduling/WeightedStaticTests.java

This PR includes the following:
* Refactored WeightedStaticScheduling to extract internal package-access classes for reading and 
writing instances to and from OR-library formatted files.
* Refactored WeightedStaticSchedulingWithSetups to extract internal package-access classes for reading and 
writing instances to and from the format of Cicirello (2003).
* Refactored test cases for WeightedStaticSchedulingWithSetups based on RefactorFirst scan
Closes #585 
Closes #595

Refactor WeightedStaticSchedulingWithSetups and WeightedStaticScheduling

---

CHANGELOG.md

Prepare release 6.2.1

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/PartiallyMatchedCrossover.java
src/main/java/org/cicirello/search/operators/permutations/TwoChangeMutation.java
src/main/java/org/cicirello/search/operators/permutations/UniformPartiallyMatchedCrossover.java
src/test/java/org/cicirello/search/operators/permutations/PMXAndRelatedTests.java
src/test/java/org/cicirello/search/operators/permutations/TwoChangeMutationTests.java

Refactored and optimized PartiallyMatchedCrossover, UniformPartiallyMatchedCrossover, and TwoChangeMutation.

Refactored and optimized permutation crossover operators

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/NonWrappingOrderCrossover.java
src/main/java/org/cicirello/search/operators/permutations/OrderCrossover.java
src/main/java/org/cicirello/search/operators/permutations/OrderCrossoverTwo.java
src/main/java/org/cicirello/search/operators/permutations/UniformOrderBasedCrossover.java

Refactored and optimized:
* NonWrappingOrderCrossover
* OrderCrossover
* OrderCrossoverTwo
* UniformOrderBasedCrossover

Refactored and optimized OX, OX2, NWOX, and UOBX

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/NaiveAlwaysMutateGeneration.java
src/main/java/org/cicirello/search/evo/NaiveGenerationalEvolutionaryAlgorithm.java
src/main/java/org/cicirello/search/evo/NaiveSimpleGeneration.java
src/test/java/org/cicirello/search/evo/NaiveGenerationalEATests.java

Added the NaiveGenerationalEvolutionaryAlgorithm class, which includes:
* Adding NaiveGenerationalEvolutionaryAlgorithm: This is the typical implementation of a generational EA. It is temporarily added to the library in this release for a specific research purpose. You should instead use the existing GenerationalEvolutionaryAlgorithm class, which is logically and statistically equivalent, as well as highly optimized.
* The new NaiveGenerationalEvolutionaryAlgorithm class is deprecated upon introduction. It is temporarily added to the library in this release for a specific research purpose. Once that research purpose is served, it will be removed from the library with no further notice. That future removal will not be considered a breaking change due to the prominent notice in the class's …

Added the NaiveGenerationalEvolutionaryAlgorithm class

---

CHANGELOG.md

Prepare release 6.3.0

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/permutations/PositionBasedCrossover.java
src/test/java/org/cicirello/search/operators/permutations/PBXTests.java

Added Position Based Crossover (PBX), a crossover operator for permutations.
Closes #642

Added Position Based Crossover (PBX)

---

CHANGELOG.md

Prepare release 6.4.0

---

CHANGELOG.md
src/main/java/org/cicirello/search/evo/AbstractWeightedSelection.java
src/main/java/org/cicirello/search/ss/AbstractStochasticSampler.java

* Fixed potential int overflow in average computation in AbstractWeightedSelection.
* Fixed potential int overflow in average computation in AbstractStochasticSampler.
Closes #658 
Closes #659

Fixed potential int overflow in average computation

---

CHANGELOG.md
spotbugs-exclude.xml
src/main/java/org/cicirello/search/operators/integers/IntegerVectorInitializer.java
src/main/java/org/cicirello/search/problems/BoundMax.java
src/test/java/org/cicirello/search/problems/BoundMaxTests.java

Fixed symmetric issue with equals method of BoundMax and its superclass.
Closes #650 
Closes #653

Fixed issues with BoundMax equals method

---

src/main/java/org/cicirello/search/operators/permutations/package-info.java
src/test/java/org/cicirello/search/ss/IterativeSamplingTests.java

Added citations to articles on permutation operators to documentation.

Added citations to articles on permutation operators to documentation

---

.github/workflows/maven-publish.yml
CHANGELOG.md
README.md
pom.xml

Discontinued publishing a `jar-with-dependencies` (only a breaking change for those manually downloading library).
Closes #720

Discontinued generation of jar-with-dependencies

---

CHANGELOG.md
src/main/java/org/cicirello/search/SimpleMetaheuristic.java
src/main/java/org/cicirello/search/evo/StochasticUniversalSampling.java
src/main/java/org/cicirello/search/operators/bits/TwoPointCrossover.java
src/main/java/org/cicirello/search/operators/integers/TwoPointCrossover.java
src/main/java/org/cicirello/search/operators/permutations/CycleAlphaMutation.java
src/main/java/org/cicirello/search/operators/permutations/CycleMutation.java
src/main/java/org/cicirello/search/operators/permutations/PositionBasedCrossover.java
src/main/java/org/cicirello/search/operators/permutations/ScrambleMutation.java
src/main/java/org/cicirello/search/operators/permutations/UndoableScrambleMutation.java
src/main/java/org/cicirello/search/operators/permutations/UndoableUniformScrambleMutation.java
src/main/java/org/cicirello/search/operators/permutations/UniformScrambleMutation.java
src/main/java/org/cicirello/search/operators/permutations/WindowLimitedScrambleMutation.java
src/main/java/org/cicirello/search/operators/permutations/WindowLimitedUndoableScrambleMutation.java
src/main/java/org/cicirello/search/operators/reals/TwoPointCrossover.java
src/main/java/org/cicirello/search/problems/binpack/BinPacking.java
src/test/java/org/cicirello/search/sa/ExponentialCoolingTests.java
src/test/java/org/cicirello/search/sa/LinearCoolingTests.java
src/test/java/org/cicirello/search/sa/LogarithmicCoolingTests.java
src/test/java/org/cicirello/search/sa/ModifiedLamOriginalTests.java
src/test/java/org/cicirello/search/sa/ModifiedLamTests.java
src/test/java/org/cicirello/search/sa/ParamFreeExponentialCoolingTests.java
src/test/java/org/cicirello/search/sa/ParamFreeLinearCoolingTests.java
src/test/java/org/cicirello/search/sa/SelfTuningLamTests.java

Refactored and improved the following classes to utilize new functionality from the dependencies on core and rho-mu:
* BinPacking
* CycleAlphaMutation
* CycleMutation
* ScrambleMutation
* StochasticUniversalSampling
* TwoPointCrossover (versions for BitVectors, IntegerVectors, and RealVectors)
* UndoableScrambleMutation
* UndoableUniformScrambleMutation
* UniformScrambleMutation
* WindowLimitedScrambleMutation
* WindowLimitedUndoableScrambleMutation
Closes #721

Refactored to use new functionality from rho-mu 4.0.0 and core 2.7.0

---

CHANGELOG.md
README.md
pom.xml
src/main/java/module-info.java

Prepare major release 7.0.0

---

.github/workflows/docs.yml

Fix docs workflow with new maven javadoc directory.

Fix docs workflow with new maven javadoc directory

---

src/main/java/module-info.java

Added ECTA 2024 paper to module documentation.

Added ECTA 2024 paper to module documentation

---

CHANGELOG.md
src/main/java/org/cicirello/search/operators/integers/IntegerVectorInitializer.java

Refactored IntegerVectorInitializer based on RefactorFirst analysis, which identified it as a god class.
Closes #769

Refactored IntegerVectorInitializer based on RefactorFirst analysis

---

CHANGELOG.md

Prepare release 7.0.1

---

.github/workflows/manual-deploy.yml
.github/workflows/maven-publish.yml
CHANGELOG.md
pom.xml

Maven Central migration from the old OSSRH to the new Central

Maven Central migration
