cicirello/Chips-n-Salsa

- .github/workflows/api-webpage-sitemap.yml
- CHANGELOG.md
- README.md
- docs/api/index-all.html
- docs/api/org/cicirello/search/problems/scheduling/WeightedStaticSchedulingWithSetups.html
- docs/sitemap.xml
- pom.xml
- src/org/cicirello/search/problems/scheduling/WeightedStaticSchedulingWithSetups.java
- tests/org/cicirello/search/problems/scheduling/WeightedStaticSetupsTests.java
* Parser for benchmark scheduling instance data files for single machine scheduling problems with weights, duedates, and sequence-dependent setup times (Closes #66 ).
* Other misc minor changes (e.g., github actions version updates, etc)
> Parser for benchmark scheduling instance data files

- CHANGELOG.md
- src/org/cicirello/search/operators/permutations/CycleMutation.java
- src/org/cicirello/search/operators/permutations/ReversalMutation.java
- src/org/cicirello/search/operators/permutations/ScrambleMutation.java
- src/org/cicirello/search/operators/permutations/SwapMutation.java
- src/org/cicirello/search/operators/permutations/TwoChangeIterator.java
- src/org/cicirello/search/operators/permutations/TwoChangeMutation.java
- src/org/cicirello/search/operators/permutations/UndoableScrambleMutation.java
- src/org/cicirello/search/operators/permutations/UndoableUniformScrambleMutation.java
- src/org/cicirello/search/operators/permutations/UniformScrambleMutation.java
- src/org/cicirello/search/operators/permutations/WindowLimitedScrambleMutation.java
- src/org/cicirello/search/operators/permutations/WindowLimitedUndoableScrambleMutation.java
- tests/org/cicirello/search/operators/permutations/IterableMutationTests.java
- tests/org/cicirello/search/operators/permutations/PermutationMutationTests.java
Added new permutation mutation operators, including UniformScrambleMutation, TwoChangeMutation, and CycleMutation. Other minor changes to permutation mutation ops, such as documentation updates, code optimizations and other code improvements.
* Closes #228 
* Closes #230 
* Closes #231
> Added new permutation mutation operators

- .lift.toml
- CHANGELOG.md
- pom.xml
We've been executing the build with JDK 11, but targeting Java 8+. We are changing the minimum supported Java version to Java 11. The build process has been migrated to target Java 11. The purpose of this change is multifaceted. First, it gives us access to newer Java features. Second, the dependencies have been migrated to Java 11, so in order to upgrade dependency versions, this migration to Java 11 is necessary.
Closes #287
> Migrated build process to target Java 11

- CHANGELOG.md
- src/main/java/org/cicirello/search/evo/BiasedShiftedFitnessProportionalSelection.java
- src/main/java/org/cicirello/search/evo/BiasedShiftedStochasticUniversalSampling.java
- src/main/java/org/cicirello/search/evo/FitnessProportionalSelection.java
- src/main/java/org/cicirello/search/evo/ShiftedFitnessProportionalSelection.java
- src/main/java/org/cicirello/search/evo/ShiftedStochasticUniversalSampling.java
- src/test/java/org/cicirello/search/evo/SelectionOperatorTests.java
Added the following shifted fitness variations of fitness proportional selection operators:
* ShiftedFitnessProportionalSelection, which is a variation of FitnessProportionalSelection that uses transformed fitness values that are shifted so that the minimum is equal to 1, enabling safe use with negative fitness values.
* ShiftedStochasticUniversalSampling, which is a variation of StochasticUniversalSampling that uses transformed fitness values that are shifted so that the minimum is equal to 1, enabling safe use with negative fitness values.
* BiasedShiftedFitnessProportionalSelection, which is a variation of BiasedFitnessProportionalSelection that uses transformed fitness values that are shifted so that the minimum is equal to 1, enabling safe use with negative fitness values.
* …
> Shifted fitness variations of fitness proportional selection operators

- src/main/java/org/cicirello/search/evo/GenerationalEvolutionaryAlgorithm.java
- src/test/java/org/cicirello/search/evo/GenerationalEANoPTTests.java
Added constructors to GenerationalEvolutionaryAlgorithm for a default ProgressTracker.
> Added constructors to GenerationalEvolutionaryAlgorithm for a default ProgressTracker

- CHANGELOG.md
- src/main/java/org/cicirello/search/ProgressTracker.java
- src/main/java/org/cicirello/search/SolutionCostPair.java
- src/main/java/org/cicirello/search/evo/AbstractEvolutionaryAlgorithm.java
- src/main/java/org/cicirello/search/evo/GenerationalEvolutionaryAlgorithm.java
- src/main/java/org/cicirello/search/evo/GenerationalMutationOnlyEvolutionaryAlgorithm.java
- src/main/java/org/cicirello/search/evo/MutationOnlyGeneticAlgorithm.java
- src/test/java/org/cicirello/search/ProgressTrackerTests.java
- src/test/java/org/cicirello/search/SolutionCostPairTests.java
- src/test/java/org/cicirello/search/evo/GenerationalEANoPTTests.java
- src/test/java/org/cicirello/search/evo/GenerationalEATests.java
- src/test/java/org/cicirello/search/hc/HillClimberTests.java
* Next release will be 4.0.0 due to breaking changes.
* Added GenerationalMutationOnlyEvolutionaryAlgorithm, moving the mutation-only EA
functionality into this new class from the existing GenerationalEvolutionaryAlgorithm
class.
* Refactored evolutionary algorithm classes to improve maintainability, and ease
integration of planned future functionality.
* Removed all mutation-only EA functionality from the GenerationalEvolutionaryAlgorithm,
moving that functionality into the new GenerationalMutationOnlyEvolutionaryAlgorithm. This
was done for maintainability. It is a breaking-change, although it should affect minimal
users as the GenerationalEvolutionaryAlgorithm was just introduced. For this using it
simply use the new GenerationalMutationOnlyEvolutionaryAlgorithm class where you will …
> Refactored the new evolutionary algorithm classes

- .github/workflows/build.yml
- .lift.toml
- CHANGELOG.md
- src/main/java/org/cicirello/search/problems/IntegerCostOptimizationProblem.java
- src/main/java/org/cicirello/search/problems/OptimizationProblem.java
- src/main/java/org/cicirello/search/problems/PermutationToBitVectorProblem.java
- src/main/java/org/cicirello/search/problems/Problem.java
- src/test/java/org/cicirello/search/problems/PermutationBitVectorTests.java
Added the class PermutationToBitVectorProblem, which includes wrappers of OptimizationProblem<Permutation> and IntegerCostOptimizationProblem<Permutation> implementing OptimizationProblem<BitVector> and IntegerCostOptimizationProblem<BitVector>. The purpose is to enable easily comparing performance of Permutation vs BitVector representations on a problem without the need to reimplement the problem for each representation. The mapping uses a simple classic mapping from bits to permutations.
Closes #355
> Transformation from Permutation problem to BitVector problem

- CHANGELOG.md
- src/main/java/org/cicirello/search/problems/tsp/RandomTSPMatrix.java
- src/main/java/org/cicirello/search/problems/tsp/TSP.java
- src/test/java/org/cicirello/search/problems/tsp/RandomTSPMatrixTests.java
- src/test/java/org/cicirello/search/problems/tsp/TSPTests.java
Implemented the optional method, minCost, of the OptimizationProblem and IntegerCostOptimizationProblem classes in all of the various TSP implementations to return a simple, extremely loose, lower bound of 0, to enable using the InverseCostFitnessFunction class that require a finite lower bound. The default implementation of that method otherwise returns negative infinity.
> Fix tsp lower bounds

- CHANGELOG.md
- pom.xml
- src/test/java/org/cicirello/search/evo/SelectionOperatorTests.java
Bumped rho-mu to 1.2.0. Also edited test cases for linear rank selection.
> Bumped rho-mu to 1.2.0 and edited test cases

- CHANGELOG.md
- src/main/java/org/cicirello/search/problems/LargestCommonSubgraph.java
- src/main/java/org/cicirello/search/problems/QuadraticAssignmentProblem.java
- src/test/java/org/cicirello/search/problems/LCSTests.java
- src/test/java/org/cicirello/search/problems/QAPTests.java
Added the following:
* Factory method QuadraticAssignmentProblem.createInstance for creating QAP instances
from specified cost and distance matrices.
* Constructor for LargestCommonSubgraph class for creating instances from lists of
the edges of the two graphs.
> Added factory methods and constructors to QAP and LCS classes

- CHANGELOG.md
- pom.xml
The following needed to be done simultaneously:
* Bumped rho-mu from 1.2.0 to 2.3.0 (breaking change).
* Bumped jpt from 3.3.0 to 4.0.0 (breaking change).
> Bump rho-mu and jpt versions

- .github/workflows/docs.yml
Updated the documentation website workflow to inject web monetization meta tag into the head of each javadoc page.
> Updated documentation website workflow

- CHANGELOG.md
- src/main/java/org/cicirello/search/evo/FitnessShifter.java
- src/test/java/org/cicirello/search/evo/FitnessShifterTests.java
Added FitnessShifter class for use in combination with fitness-weighted selection operators to shift all fitnesses such that minimum fitness is 1 at the time of selection (e.g., deals with negative fitnesses, etc).
Closes #439
> Added FitnessShifter  class

- CHANGELOG.md
- src/main/java/org/cicirello/search/evo/BiasedFitnessProportionalSelection.java
- src/main/java/org/cicirello/search/evo/BiasedShiftedFitnessProportionalSelection.java
- src/main/java/org/cicirello/search/evo/BiasedShiftedStochasticUniversalSampling.java
- src/main/java/org/cicirello/search/evo/BiasedStochasticUniversalSampling.java
- src/main/java/org/cicirello/search/evo/FitnessProportionalSelection.java
- src/main/java/org/cicirello/search/evo/ShiftedFitnessProportionalSelection.java
- src/main/java/org/cicirello/search/evo/ShiftedStochasticUniversalSampling.java
- src/main/java/org/cicirello/search/evo/StochasticUniversalSampling.java
- src/test/java/org/cicirello/search/evo/GATests.java
- src/test/java/org/cicirello/search/evo/MutationOnlyGATests.java
- src/test/java/org/cicirello/search/evo/SelectionOperatorTests.java
Deprecated the following:
* ShiftedFitnessProportionalSelection, replaced by combination of FitnessShifter with FitnessProportionalSelection.
* ShiftedStochasticUniversalSampling, replaced by combination of FitnessShifter with StochasticUniversalSampling.
* BiasedShiftedFitnessProportionalSelection, replaced by combination of FitnessShifter with BiasedFitnessProportionalSelection.
* BiasedShiftedStochasticUniversalSampling, replaced by combination of FitnessShifter with BiasedStochasticUniversalSampling.
Closes #443
> Deprecated shifted fitness variations of fitness weighed selection operators

- CHANGELOG.md
- src/main/java/org/cicirello/search/operators/permutations/NonWrappingOrderCrossover.java
- src/test/java/org/cicirello/search/operators/permutations/OrderingRelatedCrossoverTests.java
Added Non-Wrapping Order Crossover (NWOX), a crossover operator for permutations.
Closes #455
> Added Non-Wrapping Order Crossover (NWOX)

- src/test/java/org/cicirello/search/operators/permutations/OrderingRelatedCrossoverTests.java
Fixed bug in test cases for OX and NWOX. Impossible for test cases to know for sure which random cross region was selected by the operator. Test cases currently make best guess by finding the longest contiguous sequence of fixed points between children and parents. That is not guaranteed to be foolproof, and when it is not may lead to a false test case failure. The longer the length of the permutation, the less likely such false test failures will occur. Changed test cases to only do that check for permutation lengths 32 and 64 (and not the especially short permutations).
> Fixed bug in test cases for OX and NWOX

- CHANGELOG.md
- src/main/java/org/cicirello/search/operators/permutations/UniformOrderBasedCrossover.java
- src/test/java/org/cicirello/search/operators/permutations/OrderingRelatedCrossoverTests.java
Added Uniform Order-Based Crossover (UOBX), a crossover operator for permutations.
Closes #456
> Added Uniform Order-Based Crossover (UOBX)

- src/test/java/org/cicirello/search/operators/permutations/OrderingRelatedCrossoverTests.java
The OX and NWOX crossover operators involve choosing a random cross region. The test cases heuristically guess (from the result) what that cross region was. The operators don't store it for use afterwards, so there is no way to determine definitively. If the test case's heuristic guess is wrong, then there may be a false test failure. i.e., the operator may have done the right thing, but the test case fails because it believes the random cross region was different than it actually was. In this PR, the test cases are improved to significantly reduce the probability of one of these false failures. I believe one of these false failures should now be approximately a 1 in 1000000 to 1 in 1000000000 case.
> Improved test cases for OX and NWOX crossover operators

- src/test/java/org/cicirello/search/operators/permutations/CycleCrossoverTests.java
- src/test/java/org/cicirello/search/operators/permutations/OrderingRelatedCrossoverTests.java
- src/test/java/org/cicirello/search/operators/permutations/PMXAndRelatedTests.java
Added optional test cases for permutation crossover operators. Specifically, added a few tests in a deactivated state (i.e., no `@Test` annotation) that when activated output the results of the permutation crossover operators on small sample permutations to enable visually, manually, inspecting. The existing tests are all automated, including attempting to confirm not only valid permutations as result, but also that the specific behavior of the implemented crossover operator is as defined. These deactivated, manual tests are in place as an added mechanism to ensure correct behavior, and not just valid results, since these operators are rather complex.
These are really a run one time kind of thing, but kept in test cases as a record, and to be available to run again if any thing changes.
> Added test cases for permutation crossover operators

- CHANGELOG.md
- src/main/java/org/cicirello/search/operators/permutations/PrecedencePreservativeCrossover.java
- src/test/java/org/cicirello/search/operators/permutations/PPXTests.java
Added two-point version of Precedence Preservative Crossover (PPX), a crossover operator for permutations.
Closes #459
> Added two-point version of Precedence Preservative Crossover (PPX)

- CHANGELOG.md
- src/main/java/org/cicirello/search/operators/permutations/PrecedencePreservativeCrossover.java
- src/main/java/org/cicirello/search/operators/permutations/UniformPrecedencePreservativeCrossover.java
- src/test/java/org/cicirello/search/operators/permutations/PPXTests.java
Added the uniform version of Precedence Preservative Crossover (PPX), a crossover operator for permutations.
Closes #472
> Added the uniform version of Precedence Preservative Crossover (PPX)

- .github/workflows/jitpack-build.yml
Improved jitpack-build.yml workflow for ahead-of-time jitpack snapshot builds by curling the maven-metadata.xml rather than the directory of the snapshot.
Closes #494
> Improved ahead-of-time jitpack snapshot builds

- .github/workflows/maven-publish.yml
Improved release workflow for ahead-of-time jitpack release builds by curling the maven-metadata.xml rather than the directory of the release.
Closes #495
> Improved jitpack ahead of time release builds

- src/main/java/org/cicirello/search/operators/reals/UndoableUniformMutation.java
- src/main/java/org/cicirello/search/operators/reals/UniformMutation.java
- src/test/java/org/cicirello/search/operators/reals/UniformMutationTests.java
Added a factory method in Uniform mutation operator classes (for real-valued representations) that constrains result to an interval.
Closes #513
> Option to constrain result of uniform mutation to an interval

- CHANGELOG.md
- pom.xml
Configuration of maven-shade-plugin fixed to suppress generation of dependency-reduced pom to avoid breaking transitive dependencies for the regular jar of the library.
Closes #545
> Configuration of maven-shade-plugin fixed to suppress generation of dependency-reduced pom

- CHANGELOG.md
- src/main/java/org/cicirello/search/SolutionCostPair.java
- src/test/java/org/cicirello/search/SolutionCostPairTests.java
* Fixed double comparison in SolutionCostPair.compareTo(SolutionCostPair).
* Added missing equals and hashCode methods to SolutionCostPair.
Closes #647 
Closes #648
> Fixed SolutionCostPair.compareTo and added missing equals and hashCode

- CHANGELOG.md
- src/main/java/org/cicirello/search/problems/scheduling/WeightedStaticSchedulingWithSetupsWriter.java
Fixed end of line characters when writing weighted static scheduling instances to file.
Closes #651
> Fixed end of line chars when writing scheduling instances to file

- CHANGELOG.md
- src/main/java/org/cicirello/search/problems/scheduling/WeightedStaticScheduling.java
WeightedStaticScheduling: fixed constants that should be static fields.
Closes #656
> Fixed constants that should be static fields

- CHANGELOG.md
- src/main/java/org/cicirello/search/operators/permutations/BlockInterchangeIterator.java
Improved BlockInterchangeIterator.rollback() by adding missing default case to switch statement. This was not a bug, strictly speaking, because the missing default case should do nothing. But the fact that it was missing may have lead one to question if something is not handled correctly. Added explicit default case that does nothing with a comment explaining why.
Closes #662
> Improved BlockInterchangeIterator.rollback()

- CHANGELOG.md
- src/main/java/org/cicirello/search/problems/LargestCommonSubgraph.java
Performance improvement to LargestCommonSubgraph: a private inner class is now static since it doesn't require reference to surrounding instance.
Closes #654
> Performance improvement to LargestCommonSubgraph

- spotbugs-exclude.xml
Configured SpotBugs for false positive. The floating-point equality checks here are deliberate. The values are not result of be computed. They are settings. The equals method is checking if two instances have been configured exactly the same.
Closes #660
> Configured SpotBugs for false positive

- CHANGELOG.md
- spotbugs-exclude.xml
SpotBugs: exclude false positive. The superclass defines hashCode appropriately, and the subclass doesn't add any additional state. All a hashCode method would do would be to call the superclass one,
Closes #649
> SpotBugs: exclude false positive

- CHANGELOG.md
- spotbugs-exclude.xml
- src/main/java/org/cicirello/search/ProgressTracker.java
- src/main/java/org/cicirello/search/operators/integers/IntegerValueInitializer.java
- src/main/java/org/cicirello/search/operators/integers/IntegerVectorInitializer.java
- src/main/java/org/cicirello/search/operators/integers/RandomValueChangeMutation.java
- src/main/java/org/cicirello/search/operators/integers/UndoableRandomValueChangeMutation.java
- src/main/java/org/cicirello/search/operators/reals/RealValueInitializer.java
- src/main/java/org/cicirello/search/operators/reals/RealVectorInitializer.java
- src/main/java/org/cicirello/search/problems/BoundMax.java
- src/test/java/org/cicirello/search/operators/integers/IntegerValuedInitializerTests.java
- src/test/java/org/cicirello/search/operators/integers/RandomChangeTests.java
- src/test/java/org/cicirello/search/operators/reals/RealValuedInitializerTests.java
- src/test/java/org/cicirello/search/problems/BoundMaxTests.java
Removed unnecessary equals() and hashCode() methods from evolutionary operators. These were nonsensical. You should never need to compare these for equality, etc. 
Closes #668
> Removed unnecessary equals() and hashCode() methods from evolutionary operators

- CHANGELOG.md
- spotbugs-exclude.xml
- src/main/java/org/cicirello/search/concurrent/TimedParallelMultistarter.java
Return a copy from TimedParallelMultistarter.getSearchHistory() rather than reference to field.
Closes #670
> Fixed TimedParallelMultistarter.getSearchHistory()  to return a copy

- CHANGELOG.md
- src/main/java/org/cicirello/search/operators/reals/RealVectorInitializer.java
Refactored RealVectorInitializer based on RefactorFirst analysis, which identified it as a god class.
Closes #768
> Refactored RealVectorInitializer based on RefactorFirst analysis
